### PR TITLE
Update React Native from 0.57.8 to 0.61.5

### PR DESCRIPTION
**Pull request by Bruno-Furtado**
- [x] Update React Native from 0.57.8 to 0.61.5

### CODE REVIEW

**Comment by wagnerdelima** [comment]
@Bruno-Furtado any idea when you would build the npm version?

**Comment by wagnerdelima** [comment]
Besides, @Bruno-Furtado, I just wanted to ask if this lib works in managed apps or do I have to eject the app? Thanks.

**Comment by Bruno-Furtado** [comment]
@wagnerdelima 

> @Bruno-Furtado any idea when you would build the npm version?

I published the version 1.1.1 a few seconds ago:
_(I pushed some new code, so please update your master branch)._

Screen Shot 2020-01-02 at 08 36 27

> Besides, @Bruno-Furtado, I just wanted to ask if this lib works in managed apps or do I have to eject the app? Thanks.

Maybe I didn't understand your question, but the library is a standard React Native library, I mean: it will work like all other React Native libraries.

**Comment by wagnerdelima** [comment]
I am getting an error when I import the library: Null not an object (evaluating 'RNSmsRetrieverModule.requestPhoneNumber')

**Comment by wagnerdelima** [comment]
@Bruno-Furtado sorry I am not an export in react native.

**Comment by Bruno-Furtado** [comment]
@wagnerdelima can you try to use the example project?
1. Clone the repo
2. Enter on the `example` folder
3. Run `npm install`
4. Run the project

**Comment by devstarman** [comment]
@Bruno-Furtado I think that @wagnerdelima mentioned expo-managed app (https://docs.expo.io/)
Actually I happen to have the same problem working with expo. Current Expo SDK 36.0 links to React Native 0.61.4 and there is no way to update only React Native in expo-managed app.
So working with expo there is error:
"TypeError: null is not an object (evaluating 'RNSmsRetrieverModule.requestPhoneNumber')"
(react-native-sms-retriever\index.js:6:28)

Do you suggest any workaround?

**Comment by yuritoledo** [comment]
@Bruno-Furtado  ^

**Comment by hnabbasi** [comment]
I am having the same issue,

expo sdk: 37.0
react-native: 0.61.5

On Android, I get this error:
```
TypeError: null is not an object (evaluating 'RNSmsRetrieverModule.requestPhoneNumber')
<global> index.js:6:28
loadModuleImplementation require.js:322:6
. . .
```

**Comment by FaizalKhan-Hub** [comment]
I am having the same issue,

expo sdk: 37.0
react-native: 0.61.5

On Android, I get this error:

TypeError: null is not an object (evaluating 'RNSmsRetrieverModule.requestPhoneNumber')
<global> index.js:6:28
loadModuleImplementation require.js:321:11
plz help me

. . .

**Pull request merged**
