### PR TITLE
Changed support library imports to AndroidX.

### PR DESCRIPTION
**Pull request by cmasus**
This will resolve open Issue #14 Support for AndroidX and React Native v0.60

I suggest changing major version of this package after merging, as it wont work anymore on RN version less than 0.60.

### CODE REVIEW

**Comment by wagnerdelima** [comment]
Is this ever going to be merged?

**Comment by wagnerdelima** [comment]
@Bruno-Furtado is this project still alive? Thank you very much.

**Comment by Bruno-Furtado** [comment]
@cmasus / @wagnerdelima  / @BillTuan,

I worked on some improvements and I updated the AndroidX on the [version 1.1.0](https://github.com/Bruno-Furtado/react-native-sms-retriever/releases/tag/1.1.0) of the module: https://github.com/Bruno-Furtado/react-native-sms-retriever/pull/22

**Comment by wagnerdelima** [comment]
thank you @Bruno-Furtado . Let's get this year rolling with lots of things done. Happy new year.

**Pull request closed without merging**
